#!/bin/bash
job_file="template.job"

# Select gpu or cpu
echo -n "Do you want to use gpu?(y/n) "
read -r use_gpu
if [[ $use_gpu = "y" ]]; then
    echo "#PBS -l select=1:ncpus=8:ngpus=1" > $job_file
    echo "#PBS -q gpu" >> $job_file
else
    echo "How many cores of CPU do you need?"
    
    # reference: https://stackoverflow.com/questions/50521798/how-to-check-if-a-number-is-within-a-range-in-shell
    while :; do
        read -p "Enter the number of cores(1-64): " cores
        [[ $cores =~ ^[0-9]+$ ]] || { echo "Enter a valid number"; continue; }
        if ((1 <= cores && cores <= 64)); then
            break;
        else
            echo "number out of range, try again"
        fi
    done

    echo "#PBS -l select=1:ncpus=$cores:mpiprocs=1:ompthreads=$cores" > $job_file
    echo "#PBS -q workq" >> $job_file
fi
echo "#PBS -j oe" >> $job_file

# Ask Job Name
echo -n "Your job name: "
read -r job_name
echo -n "Your conda environment name: "
read -r env_name

echo "#PBS -N $job_name" >> $job_file
echo "" >> $job_file
echo "export PYTHONPATH=\$PYTHONPATH:$PWD" >> $job_file
echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:${HOME}/anaconda3/lib/" >> $job_file
echo "source ~/.bashrc" >> $job_file
echo "cd $PWD" >> $job_file
echo "conda activate $env_name" >> $job_file
echo "" >> $job_file
echo 'echo "=========================================================="' >> $job_file
echo 'echo "Starting on : $(date)"' >> $job_file
echo 'echo "Running on node : $(hostname)"' >> $job_file
echo 'echo "file directory : $(pwd)"' >> $job_file
echo 'echo "file job ID : $PBS_JOBID"' >> $job_file
echo 'echo "=========================================================="' >> $job_file
echo "## write donw your command..." >> $job_file
echo "" >> $job_file

echo 'echo "Job Ended at $(date)"' >> $job_file
echo 'echo "======================================================="' >> $job_file
echo "" >> $job_file
echo "conda deactivate" >> $job_file