#!/bin/bash
job_file="template.job"
template_folder=$(dirname "$0")/template

# global varaibles
job_name=""
cores=0
work_dir=""
conda_name=""

function askCores(){
    max=$1
    echo "How many cores of CPU do you need?" 
    # reference: https://stackoverflow.com/questions/50521798/how-to-check-if-a-number-is-within-a-range-in-shell
    while :; do
        read -p "Enter the number of cores(1-$max): " cores
        [[ $cores =~ ^[0-9]+$ ]] || { echo "Enter a valid number"; continue; }
        if ((1 <= cores && cores <= max)); then
            break;
        else
            echo "number out of range, try again"
        fi
    done
}

function askWorkDir(){
    echo "Where does the folder your program run in?"
    echo "0) same as the path of job file: \$PBS_O_WORKDIR" 
    echo "1) the current folder: $PWD"
    echo "2) the parent of the folder: $(dirname $PWD)"
    echo "3) others"
    while :; do
        echo -n "Enter your index: "
        read -r index
        case $index in
            "0")
            work_dir='\$PBS_O_WORKDIR'
            break
            ;;
            "1")
            work_dir="$PWD"
            break
            ;;
            "2")
            work_dir="$(dirname $PWD)"
            break
            ;;
            "3")
            echo -n "Enter your path: "
            read -r work_dir
            break
            ;;
            *) echo "invalid input" ;;
        esac
    done
}

function askCondaEnv(){
    while :; do
        read -p "Does your program need to use conda?(y/n) " yn
        case $yn in
        [Yy]* )
            read -p "Please enter your name of conda enviroment: " conda_name
            break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
    done
}

function askJobName(){
    echo -n "Your job name: "
    read -r job_name
}

askJobName
askWorkDir
askCondaEnv

if [ -z "$conda_name" ]; then
    conda_activate=""
    conda_deactivate=""
else
    conda_activate="conda activate $conda_name"
    conda_deactivate="conda deactivate"
fi

echo "Do you need any other of softwares?"
echo "0) No"
echo "1) Yes, QChem"
echo "2) Yes, VASP"
while :; do
    read -p "Enter your index: " index
    case "$index" in
    # No
    "0") 
        # Select gpu or cpu
        echo -n "Do you want to use gpu?(y/n) "
        read -r use_gpu
        if [[ $use_gpu = "y" ]]; then
            header="$template_folder/headers/gpu.txt"
            askCores 8
        else
            header="$template_folder/headers/cpu.txt"
            askCores 64
        fi
        export_string=""
        export_string="export PYTHONPATH=\$PYTHONPATH:WORKDIR\n"
        export_string="${export_string}export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:${HOME}/anaconda3/lib/\n"
        export_string="${export_string}source ~/.bashrc\n"
        break
        ;;
    # QChem
    "1")
        header="$template_folder/headers/cpu.txt" 
        program="$template_folder/information/qchem.txt"

        askCores 64
        break
        ;;
    # VASP
    "2") 
        header="$template_folder/headers/mpi.txt"
        program="$template_folder/information/vasp.txt"

        askCores 64
        break
        ;;
    *) echo "invalid input" ;;
    esac
done

echo "#!/usr/bin/bash" > $job_file
cat $header >> $job_file
echo "cd WORKDIR" >> $job_file
[ -z "$export_string" ] || printf "%b" "$export_string" >> $job_file
[ -z "$conda_activate" ] || echo "$conda_activate" >> $job_file
cat $template_folder/information/start.txt >> $job_file
echo "" >> $job_file
[ -z "$program" ] || cat $program >> $job_file
echo "" >> $job_file
cat $template_folder/information/end.txt >> $job_file
[ -z "$conda_deactivate" ] || echo "$conda_deactivate" >> $job_file

sed -i "s/CORES/$cores/g" $job_file
sed -i "s/NAME/$job_name/g" $job_file
sed -i "s|WORKDIR|$work_dir|g" $job_file
