#!/bin/bash
# Delete jobs by given two id(start and end)

if [ $# -ne 2 ]; then
    echo "Illegal number of parameters" >&2
    exit 1
fi
dir_path=$(dirname "$0")
BEGIN=$1
END=$2
$dir_path/ql $USER | while read job_id;
do
    if [[ $BEGIN -le $job_id && $job_id -le $END ]]; then
        qdel $job_id
    fi
done
