#!/bin/bash
# Query job name by given a job id

job_id=$1
order=$2
tmpfile=$(mktemp -p ~)
trap "rm $tmpfile" EXIT
if stderr=$(tracejob $job_id  > $tmpfile 2> /dev/null); then
    cat $tmpfile |grep "job name"|sed "s/.*job name = \(.*\),.*/\1 $2/"
else
    echo "\@_@/expiration"
fi
 